config/routes.rb
PopHealth::Application.routes.draw do

  resources :practices
	
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_for :users do 
  	get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  
  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  put "admin/upload_patients"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
	delete "admin/remove_providers" #added for button, ssiddiqui
	delete "providers/remove"
	get "admin/user_profile"
	post "measures/export_report"
	post "measures/provider_report"
	post 'admin/remove_end_dates'
	get "admin/patient_list"
	get "measures/measure_table"
	get "admin/delete_provider"
	delete 'admin/remove_practice_patients'
	post 'admin/remove_practice_patients'
	post 'measures/export_patients'
	post "admin/set_user_practice"
	
	delete "measures/remove_selections" #added for button, ssiddiqui
	delete "logs/delete_logs"
	
	match 'admin/edit_teams/:id', :to => 'admin#edit_teams', :via => [ :get, :post ] # added from bstrezze
	match 'admin/delete_user/:id', :to => 'admin#delete_user', :via => [ :get, :post, :delete] # added by ssiddiqui

  get "logs/index"
  post "logs/index" #added for log filters
  
  match 'measures', :to => 'measures#index', :as => :dashboard, :via => :get
  match "measure/:id(/:sub_id)/providers", :to => "measures#providers", :via => :get
  match 'measure/:id(/:sub_id)', :to => 'measures#show', :as => :measure, :via => :get
  match 'measures/result/:id(/:sub_id)', :to => 'measures#result', :as => :measure_result, :via => :get
  match 'measures/definition/:id(/:sub_id)', :to => 'measures#definition', :as => :measure_definition, :via => :get
  match 'measures/patients/:id(/:sub_id)', :to => 'measures#patients', :as => :patients, :via => :get
  match 'measure/:id/select', :to => 'measures#select', :as => :select, :via => :post
  match 'measure/:id/remove', :to => 'measures#remove', :as => :remove, :via => :delete
  match 'measures/measure_patients/:id(/:sub_id)', :to=>'measures#measure_patients', :as => :measure_patients, :via=> :get
  match 'measures/measure_report', :to=>'measures#measure_report', :as => :measure_report, :via=> :get
  match 'measures/patient_list/:id(/:sub_id)', :to=>'measures#patient_list', :as => :patient_list, :via=> :get
  match 'measures/period', :to=>'measures#period', :as => :period, :via=> :post
  
  match 'provider/:npi', :to => "measures#index", :as => :provider_dashboard, :via => :get
  
  match 'records', :to => 'records#create', :via => :post
  
  match 'patients', :to => 'patients#index', :via => :get
  match 'patients/show/:id', :to => 'patients#show'
  match 'patients/toggle_excluded/:id/:measure_id(/:sub_id)', :to => 'patients#toggle_excluded', :via => :post
  
	root :to => 'measures#index'
  
  resources :measures do
    member { get :providers }
  end
  
  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end
   
    member do
      get :merge_list
      put :merge
    end
  end
  
  resources :teams
  

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  
  # load resource must be before authorize resource
  load_resource except: %w{index}
  authorize_resource
  before_filter :authenticate_user!
  
  add_breadcrumb 'Providers', :providers_url
  
  def index
    # @providers = Provider.alphabetical.page(params[:page]).per(60)
    @providers = Provider.user_filter(current_user) # added by ssiddiqui
    respond_to do |wants|
      wants.html {}
      wants.js {}
      wants.json { render json: @providers.to_json(:only => [:title, :given_name, :family_name, :npi]) }
    end
  end
  
  def show
 	 	@provider = Provider.find(params[:id])
    respond_to do |wants|
      wants.html
      wants.js
    end
  end
  
  def new
    @provider = Provider.new
    respond_to do |wants|
      wants.js {}
    end
  end
  
  def edit
    @provider = Provider.find(params[:id])
    respond_to do |wants|
      wants.js {}
    end    
    redirect_to :action => :show
  end
  
  def create
    @provider = Provider.create(params[:provider])
    # @providers = Provider.alphabetical.page(params[:page]).per(20)
		@providers = Provider.user_filter(current_user) # added by ssiddiqui
		
    respond_to do |wants|
      wants.json {
        # @provider = Provider.create(params[:data])
        render json: @provider
      }
      wants.js { }
      wants.html {}
   	end
  end
  
  def update
    @provider.update_attributes!(params[:provider])
    @providers = Provider.user_filter(current_user) # added by ssiddiqui
    
    respond_to do |wants|
      wants.html { render :action => "show" }
     # wants.js { @providers = Provider.alphabetical.page(params[:page]).per(20) }
     wants.js { @providers = Provider.user_filter(current_user) }
    end

  end
  
  def remove
  	@provider = Provider.by_id(params[:id])	 
  	redirect_to :back
  end
  
  def merge_list
    render partial: 'merge_form'
  end
  
  def merge
   other_provider = Provider.find(params[:other_provider_id])
   @provider.merge_provider(other_provider)
   other_provider.destroy
   @provider.save!
   redirect_to :action => :show
  end

end

app/helpers/providers_helper.rb
module ProvidersHelper

  def checked(providers, provider)
    providers.detect { |pv| pv.id = provider.id } ? 'checked' : ''
  end
  
  def specialties
    Provider::Specialties.sort { |s1,s2| s1[1] <=> s2[1] }.map { |pair| pair.reverse }
  end
  
  def formatted_provider_name(provider)
    return "" if provider.blank?
    return "#{provider.id}, Provider" if provider.family_name.blank? or provider.given_name.blank?
    "#{provider.family_name.upcase}, #{provider.given_name}"
  end
end

app/views/providers/_merge_form.html.erb
<%= form_tag merge_provider_path(@provider, :format => :js), :method => :put do %>
  <%= select_tag :other_provider_id, options_from_collection_for_select(@provider.merge_eligible.alphabetical, :id, :full_name)%>
  <%= submit_tag "Merge"%>
<% end %>

app/views/providers/_profile.html.erb
<h2><%= @provider.full_name %></h2>

<h4><%= @provider.specialty_name %></h4>
<h4><%= @provider.organization %></h4>
<br>
<%= link_to "edit", edit_provider_path(@provider, :format => :html), :remote => true, :method => :get, :id => "edit_provider" %>
<%= link_to "merge", merge_list_provider_path(@provider, :format => :html), :remote => true, :method => :get, :id => "merge_provider" %>

<dl>
  <dt>NPI:</dt>
  <dd><%= @provider.npi%></dd>
  <dt>Tax ID:</dt>
  <dd><%= @provider.tin%></dd>
  <dt>Phone:</dt>
  <dd><%= @provider.phone %></dd>
  <dt>Team:</dt>
  <dd><%= @provider.team.try(:name)%></dd>
</dl>


<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $("a#edit_provider").bind("ajax:success", function(event, data){ $("#content").html(data)} );
    $("a#merge_provider").bind("ajax:success", function(event, data){ $("#merge_provider").replaceWith(data) } );
  });
</script>

app/views/providers/_provider_list.html.erb
<table id="providerList" class="display table-hover table-bordered" data-source="<%= providers_url(format: "json") %>">	
	<thead id="hd" align="left">
		<tr>
		  <th>Last Name</th>
		  <th>First Name</th>
		  <th>Team</th>
	  	<th> NPI </th>
	 	 	<th/>
		</tr>
	</thead>

  <tbody>
		<%= render partial: 'provider_row', collection: providers%>
	</tbody>
</table>

app/views/providers/_provider_row.html.erb
<tr data-provider="<%= provider_row.id %>">
	<td><%= provider_row.family_name%></td>
	<td><%= provider_row.given_name%></td>
	<td><%= provider_row.team.try(:name) || "N/A" %></td>

	<td> <%= provider_row.npi %> </td>
	<td> <%= link_to "view / edit", :controller => "providers", :action => "show", :id => "#{provider_row.id}" %>  | <%= link_to "manage patients", manage_provider_patients_path(provider_row)%> | <%= link_to "view measures page", measures_path(:npi => provider_row.npi) %> 
	|
	<%= 
	 if current_user.admin?
	 		link_to 'delete', admin_delete_provider_path(:npi => provider_row.npi), confirm: "Are you sure you want to delete this provider?"
	 end
	%>
	
	</td>
</tr>

app/views/providers/_show_profile.html.erb
<style type='text/css'>
	h2{
		margin-top : 20px;
    margin-left :0px;
	}
</style>


<%= form_for @provider, {html: {id: "providerForm", class: "form-horizontal"}} do |f| %>
	
	<div id="tbl" style="margin-left:-60px">
		<div class='control-group form-inline'>
				<label class="control-label">
					Name: 
				</label>
				<div class="controls" >
						<%= f.text_field :title, 'class' => "input-mini", placeholder: "Title", :disabled => disabled %>
						<%= f.text_field :given_name, 'class' => "input-small", placeholder: "First Name", :disabled => disabled  %>
						<%= f.text_field :family_name, 'class' => "input-small", placeholder: "Last Name", :disabled => disabled  %>
				</div>
		</div>
		<div class="control-group">	
			<%= f.label :npi, "NPI:", 'class' => 'control-label', :disabled => disabled  %>
			<div class="controls">
				<%= f.text_field :npi, class: "input-small", :disabled => disabled %>
			</div>
		</div>
		<div class="control-group">	
			<%= f.label :tin, "Tax ID:", 'class' => 'control-label', :disabled => disabled%>
			<div class="controls">
				<%= f.text_field :tin, class: "input-small", :disabled => disabled %>
			</div>
		</div>
		<div class="control-group">	
			<%= f.label :team_id, "Team:", 'class' => 'control-label', :disabled => disabled %>
	 		<div class="controls">
		  	<%= f.collection_select :team_id, Team.alphabetical, :id, :name, {include_blank: true}, :disabled => disabled %>
			</div>

		</div>
		<div class="control-group">	
			<%= f.label :specialty, "Specialty:", 'class' => 'control-label', :disabled=>disabled %>
			<div class="controls">
				<%= f.select :specialty, specialties, {include_blank: true}, :disabled=>disabled, :style=>"width:300px" %>
			</div>
		</div>
		
			<% if !disabled %>
		<div class="control-group">
			<div class="controls">
				<%= submit_tag "Save", class: "btn btn-info", :style => "width:120px", :confirm => "Are you sure you want to save changes?"%>
				<%#= link_to raw("<i class=\"icon-plus-sign\"></i> Add New Provider"), new_provider_path, remote: true, class: "btn" %>
			</div>
		</div>
		<% end %>
	</div>
<% end %> <!-- end of form -->

app/views/providers/create.js.erb
$("#providerForm").replaceWith("<%= render_js partial: 'edit_profile', locals: {provider: @provider} %>")
$("#providerList").replaceWith( $("#providerList").dataTable);

<!--
$("#providerForm").replaceWith("<%= render_js partial: 'edit_profile', locals: {provider: @provider} %>")

$("#providerList").replaceWith("<%= render_js partial: 'provider_list', object: @providers, as: 'providers' %>");
-->

app/views/providers/edit.js.erb
$("#providerForm").replaceWith("<%= render_js partial: 'edit_profile', locals: {provider: @provider} %>")
$("#providerForm").effect("highlight", {color: "#ECF7F8"}, 1000);

app/views/providers/index.html.erb
<!--Added by ssiddiqui -->
<style type='text/css'>
	#rt{
    margin-left : 20px;
    margin-right: 20px;
	}
		
	#lst{
		margin-right: 20px;
		margin-left: 20px;	
	}
	
</style>



<!-- perfect template for header with buttons -->
<hr style='margin-bottom:-5px'>
<div style="padding-left:40px; padding-right:40px">
	<table class="table-condensed" style="width:100%">
		<td> <h2><strong>Providers</strong></h2> </td>

		<% if current_user.admin? %>	
			<td colspan='2' align='right'>	
				<%= link_to "Edit Teams", teams_path, remote: true, :class => "btn btn-large btn-success"%> 	
		
				<%= link_to "Delete All Providers", "/admin/remove_providers", 'method' => 'delete', 
			:confirm => "Are you sure you want to delete all the providers?", 'class' => 'btn btn-large btn-danger'%>
			</td>
		<% end %>
	</table>
</div>
<hr style="margin-top:-5px">



<div id="lst" class="container-fluid">
	<%= render partial: 'provider_list', locals: {providers: @providers} %>
	<br> <br>
	<br> <br>
</div>

app/views/providers/measure.html.erb
<div id="pageContent">
  <div id="providerReports">
    <h1>
      Providers
    </h1>
    <p class="note">
      Teams
    </p>
    <div class="measureList">
      <ul class="measureClassList">
        <% @teams.each do |team| %>
        <li>
          <label><%= team.name%></label>
          <div class="measureItemList" style="display:none">
            <ul class="providers">
              <% team.providers.alphabetical.each do |pv| %>
              <li data-provider="<%=pv.id%>" class="<%= checked(@selected_providers, pv)%> provider">
                <%= pv.full_name %>
              </li><% end %>
            </ul>
          </div>
        </li><% end %>
      </ul>
      
      <ul class="measureClassList">
        <li>
          <label>Race and Ethnicity</label>
          <div class="measureItemList" style="display:none">
            <ul class="races">
              <% @races.each do |race| %>
                <li data-race="<%=race.id%>" class="">
                  <%= race.name %>
                </li>
              <% end %>
            </ul>
          </div>
        </li>
      </ul>

      <ul class="measureClassList">
        <li>
          <label>Gender</label>
          <div class="measureItemList" style="display:none">
            <ul class="genders">
              <% @genders.each do |gender| %>
                <li data-gender="<%=gender[:key]%>" class="">
                  <%= gender[:name] %>
                </li>
              <% end %>
            </ul>
          </div>
        </li>
      </ul>
      
    </div>
  </div>
  <div id="providerMain">
    <div id="aggregate">
      <%= image_tag "loading_bar.gif", :id => "loadingAggregate", :style => "display:none" %>
      <%= render :partial => 'shared/measure_metrics', locals: {numerator: nil, denominator: nil} %>
   
      <%= render :partial => 'shared/measure_title', locals: {measure: @definition, start_date: @period_start, effective_date: @effective_date }%>
      <div class="button">
        <%= button_to 'parameters', measure_url(@definition['id'], @definition['sub_id']), :class => 'tableEdit'%> | 
        <%= button_to 'patients', patients_url(@definition['id'], @definition['sub_id']), :class => 'tableEdit'%>
      </div>
    </div>
    <table id="providerTable" border="0" cellspacing="5" cellpadding="5" >
      <tr><th colspan="4">INDIVIDUAL PROVIDER STATISTICS</th></tr>
      <tbody>
          <% @selected_providers.each do |pv| %>
            <tr class="provider" data-provider="<%=pv.id%>">
              <td class="name"><%= pv.family_name.upcase %>, <%= pv.given_name %></td>
              <td class="percent"><div class="measureProviderPopulationPercentage"></div></td>
              <td class="fraction"><%= render :partial => "shared/fraction", locals: {numerator: 0, denominator: 0} %></td>
              <td class="barChart"><%= render :partial => "shared/table_bar", locals: {numerator: 0, denominator:0, patient_count: 0, exclusions: 0}%></td>
            </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

<% content_for :head do %>
<script type="text/javascript" charset="utf-8">

var popHealth = popHealth || {};

popHealth.updateAggregate = function(num, den) {  
  popHealth.setPercent($("#aggregate #measurePopulationPercentage"), num, den);
  popHealth.setFraction($("#aggregate div.inline-fraction"), num, den);
};

popHealth.updateProviders = function(providers) {
  $("table#providerTable tr.provider").each(function() {
    var providerId = $(this).data('provider');
    var provider = providers[providerId];
    if (provider != null) {
      popHealth.updateProvider(this, provider.numerator, provider.denominator, provider.population);
    }
  });
};

popHealth.updateProvider = function(row, num, den, pop) {
  popHealth.setPercent($(row).find("td.percent .measureProviderPopulationPercentage"), num, den);
  popHealth.setFraction($(row).children("td.fraction"), num, den);
  popHealth.setBarChart($(row).find("td.barChart div.tableBar"), num, den, pop);
};

popHealth.setPercent = function(selector, num, den) {
  var percent = den != 0 ? (num / den) * 100 : 0;
  selector.html(Math.floor(percent).toString() + "%");
};

popHealth.setFraction = function(selector, num, den) {
  selector.find(".numeratorValue").html(num);
  selector.find(".denominatorValue").html(den);
};

popHealth.setBarChart = function(selector, num, den, pop) {
  var numerator_width = 0;
  var denominator_width = 0;
  if (pop != 0 && den != 0) {
    numerator_width = (num / pop) * 100;
    denominator_width = ((den - num) / pop) * 100;
  }

  selector.children("div.tableBarNumerator").animate({width: numerator_width.toString() + "%"});
  selector.children("div.tableBarDenominator").animate({width: denominator_width.toString() + "%"});
};

popHealth.makeProviderListExpandable = function() {
  $('.measureClassList li label').click(function(){
    $(this).toggleClass('open');
    $(this).siblings("div.measureItemList").toggle("blind");
  });
  $('.measureClassList li label').toggleClass('open');
  $('.measureClassList li label').siblings("div.measureItemList").toggle("blind");
};

popHealth.makeMeasuresCheckable = function() {

  $('.measureItemList li').click(function(){
    var providerRow = $("table#providerTable tr.provider[data-provider='" + $(this).data('provider') +"']");
    if ($(this).hasClass('checked')) {
      providerRow.fadeOut('fast');
    } else {
      providerRow.fadeIn('fast');
    }
    
    $(this).toggleClass('checked');
    popHealth.isPollRequestActive = true;
    popHealth.pollProviders();
  });
};

popHealth.isPollRequestActive = false;

popHealth.markLoading = function() {
  if (popHealth.isPollRequestActive) {
    $('div#measureMetrics').fadeTo('fast', 0.25, function() { if (popHealth.isPollRequestActive) $("#loadingAggregate").show(); else $('div#measureMetrics').fadeTo('fast', 1.0, function() {  }); });
  } 
};

popHealth.pollProviders = function() {
  var providerIds = $(".measureItemList ul.providers li.checked").map(function() { return $(this).data("provider");});
  var raceIds = $(".measureItemList ul.races li.checked").map(function() { return $(this).data("race");});
  var genders = $(".measureItemList ul.genders li.checked").map(function() { return $(this).data("gender");});
  var params = {'selected_provider_ids[]': $.makeArray(providerIds), 'selected_race_ids[]': $.makeArray(raceIds), 'selected_genders[]': $.makeArray(genders)};

  setTimeout(popHealth.markLoading, 300);
  
  $.getJSON("<%= providers_measure_path(measure_id: @definition['id'], sub_id: @definition['sub_id'], format: 'json')%>", params, function(data) {
    if(data.complete) popHealth.isPollRequestActive = false;

    if(data.aggregate != null) {
      popHealth.updateAggregate(data.aggregate.numerator, data.aggregate.denominator);
      
      $("#loadingAggregate").hide();
      if($("div#measureMetrics").css("opacity") < 0.3) {
        $('div#measureMetrics').fadeTo('fast', 1.0, function() {  });
      }
      
    }
    
    popHealth.updateProviders(data.providers);
    
    if(!data.complete) {
      setTimeout(function() {
        popHealth.pollProviders();
      }, 3000);
    }
  });
};


$(document).ready(function() {
  popHealth.makeProviderListExpandable();
  popHealth.makeMeasuresCheckable();
  popHealth.pollProviders();
  
});

</script>
<% end -%>

app/views/providers/new.js.erb
$("#providerForm").replaceWith("<%= render_js partial: 'edit_profile', locals: {provider: @provider} %>")

app/views/providers/provider_form.html.erb
<table id="providerList" class="display">
 
	<thead id="hd" align="left">
		<tr>
		  <th>Last Name</th>
		  <th>First Name</th>
		  <th>Team</th>
		  <th />
		</tr>
	</thead>

  <tbody>
		<%= render partial: 'provider_row', collection: providers%>
	</tbody>
</table>

app/views/providers/show.html.erb
<div id="content" style="margin-left:40px; margin-top:20px">  
	<h2><%= @provider.full_name %></h2>
	
  <% if current_user.admin? %>
		<%= render partial: 'show_profile' , locals: {disabled: false} %> 
	<% else %>
	  <%= render partial: 'show_profile', locals: {disabled: true} %>
	<% end %>
	<br>
	<%= link_to "Return to Providers Page", "/providers", class: "btn btn-success" %>
</div>

app/views/providers/show.js.erb
$("#content").html("<%= render_js(:partial =>'profile') %> ");

app/views/providers/update.js.erb
$("#providerList").replaceWith("<%= render_js partial: 'provider_list', object: @providers, as: 'providers' %>"); 

$("nav").replaceWith("<%= escape_javascript(paginate(@providers))%>");

row = $("#providerList tr[data-provider='<%= @provider.id %>']");

if (row.length > 0) {
  row.effect("highlight", {color: "#44B3BE"}, 1000);
} else{
	$("#providerTable").effect("highlight", {color: "#44B3BE"}, 1000);
};