config/routes.rb
PopHealth::Application.routes.draw do

  resources :practices
	
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_for :users do 
  	get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  
  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  put "admin/upload_patients"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
	delete "admin/remove_providers" #added for button, ssiddiqui
	delete "providers/remove"
	get "admin/user_profile"
	post "measures/export_report"
	post "measures/provider_report"
	post 'admin/remove_end_dates'
	get "admin/patient_list"
	get "measures/measure_table"
	get "admin/delete_provider"
	delete 'admin/remove_practice_patients'
	post 'admin/remove_practice_patients'
	post 'measures/export_patients'
	post "admin/set_user_practice"
	
	delete "measures/remove_selections" #added for button, ssiddiqui
	delete "logs/delete_logs"
	
	match 'admin/edit_teams/:id', :to => 'admin#edit_teams', :via => [ :get, :post ] # added from bstrezze
	match 'admin/delete_user/:id', :to => 'admin#delete_user', :via => [ :get, :post, :delete] # added by ssiddiqui

  get "logs/index"
  post "logs/index" #added for log filters
  
  match 'measures', :to => 'measures#index', :as => :dashboard, :via => :get
  match "measure/:id(/:sub_id)/providers", :to => "measures#providers", :via => :get
  match 'measure/:id(/:sub_id)', :to => 'measures#show', :as => :measure, :via => :get
  match 'measures/result/:id(/:sub_id)', :to => 'measures#result', :as => :measure_result, :via => :get
  match 'measures/definition/:id(/:sub_id)', :to => 'measures#definition', :as => :measure_definition, :via => :get
  match 'measures/patients/:id(/:sub_id)', :to => 'measures#patients', :as => :patients, :via => :get
  match 'measure/:id/select', :to => 'measures#select', :as => :select, :via => :post
  match 'measure/:id/remove', :to => 'measures#remove', :as => :remove, :via => :delete
  match 'measures/measure_patients/:id(/:sub_id)', :to=>'measures#measure_patients', :as => :measure_patients, :via=> :get
  match 'measures/measure_report', :to=>'measures#measure_report', :as => :measure_report, :via=> :get
  match 'measures/patient_list/:id(/:sub_id)', :to=>'measures#patient_list', :as => :patient_list, :via=> :get
  match 'measures/period', :to=>'measures#period', :as => :period, :via=> :post
  
  match 'provider/:npi', :to => "measures#index", :as => :provider_dashboard, :via => :get
  
  match 'records', :to => 'records#create', :via => :post
  
  match 'patients', :to => 'patients#index', :via => :get
  match 'patients/show/:id', :to => 'patients#show'
  match 'patients/toggle_excluded/:id/:measure_id(/:sub_id)', :to => 'patients#toggle_excluded', :via => :post
  
	root :to => 'measures#index'
  
  resources :measures do
    member { get :providers }
  end
  
  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end
   
    member do
      get :merge_list
      put :merge
    end
  end
  
  resources :teams
  

end

app/views/admin/_user_list.html.erb
<table class="table table-hover">
	<thead>
	<tr>
	  <th>First Name</th>
	  <th>Last Name</th>
	  <th>Username</th>
	  <th>Provider</th> 
	  <th>Staff Role</th>
	  <th>Practice</th>
	  <th>Teams</th>
	  <th>Status</th>
	 
	</tr>
	</thead>
	
	<tbody>
	<% users.each do |user|%>
	<tr >
		<td><%= user.first_name %></td>
		<td><%= user.last_name %></td>
		<td><%= user.username %></td>
		<td> <%= (user.npi)? user.npi : "N/A"%> </td>
<!--		<td>
		  <% if user.admin? -%>
		  Yes - <a href="#" class="demote" data-role="admin" data-username="<%= user.username %>">Revoke</a>
		  <% else -%>
		  No - <a href="#" class="promote" data-role="admin" data-username="<%= user.username %>">Grant</a>
		  <% end -%>
		</td>
-->		
		<td>
		  <% if user.staff_role? -%>
		  Yes - <a href="#" class="demote" data-role="staff_role" data-username="<%= user.username %>">Revoke</a>
		  <% else -%>
		  No - <a href="#" class="promote" data-role="staff_role" data-username="<%= user.username %>">Grant</a>
		  <% end -%>
		</td>
		
		<td> <%= (user.practice)? user.practice : "N/A"%></td>
		
		<td>	
			<%= link_to "View/Edit", :controller => "admin", :action => "edit_teams", :id => user._id %>
		</td>
		<td>
      <a href="#" class="<%= (user.disabled?) ? 'disable' : 'enable'%>" data-username="<%= user.username %>">
      	<%= (user.disabled?) ? 'enable' : 'disable'%>
      </a>
    </td>
      
		<td>
			<% if !(user.approved?) -%>
		  	<a href="#" class="approve btn btn-primary" data-username="<%= user.username %>">Approve</a>
		  <% end -%>	
	
			<%= link_to "View Info",{:controller => "admin", :action => "user_profile", :id => user._id}, :class => "btn btn-info"%>    
			<%= link_to "Delete User", {:controller => "admin", :action => "delete_user", :id => user._id}, 'method' => 'delete', :confirm=>"Are you sure you want to delete this user?", 'class' => 'btn btn-danger' %>    			  
		</td>
		
	</tr>
	<% end -%>
	</tbody>
</table>

app/views/admin/edit_teams.html.erb
<hr style='margin-bottom:-5px'>
	<div style="padding-left:40px; padding-right:40px">
		<table class="table-condensed" style="width:100%">
			<td> <h2>Team Assignments</h2> </td>
		</table>
	</div>
<hr style="margin-top:-5px">

<div style="margin-left:40px;margin-right:40px">
  	<% if flash[:notice] %>
			<div class="accountError">
				<font color="red"> <b> <%= flash[:notice] %> </b> </font>
			</div>
		<% end %>

		<h4> User: <%=@user.username%> (<%=@user.full_name%>)</h4>
		<br>
		   
    <%= form_for(:add_team, :controller => "admin", :action => "edit_teams", :id => @id) do |f| %>
    	<table>
    		<tr>
    			<td style="vertical-align: top; width: 75px;"><%= f.label :teams %></td>
    			<td style="vertical-align: top; width: 200px;"><%= f.collection_select :team_id, Team.alphabetical, :id, :name, {include_blank: true}, {style: "width:175px"}%></td>
    			<td style="vertical-align: top; width: 125px;"><%= f.submit "Add Team", {class: "btn btn-success", style: "width:100px"} %></td>
    		</tr>
    	</table>
    <% end %> <!-- end form -->	
  	
    
    <table id="tableTeams" class="display table table-condensed" style="width:40%">
			<tr><th colspan='2'><b>Current Teams:</b></th></tr>
			<% if (@user.teams && @user.teams.count > 0) %>
				<% @user.teams.sort.each do |team| -%>
					<tbody >
						<td align="left"><%= MONGO_DB['teams'].find({_id: team}).to_a[0]["name"] %></td>
						<td align="right" width="30px">
						    <%= form_for(:remove_team, :controller => "admin", :action => "edit_teams", :id => @id) do |f| %>
						    	<%= f.hidden_field :team_id, :value => team %>
								<%= submit_tag "Remove", {class: "btn btn-danger", confirm: "Are you sure?"} %>
						    <% end %>
						</td>
					</tbody>
				<% end %>
			<% else %>
				<tr><td>No teams assigned</td><td>&nbsp;</td></tr>
			<% end %>
		</table>	
		
</div>

app/views/admin/patient_list.html.erb
<hr style='margin-bottom:-5px'>
<div style="padding-left:40px; padding-right:40px">
	<table class="table-condensed" style="width:100%">
		<td> <h2><strong>Patient List</strong></h2> </td>
		<td colspan='2' align='right'>	
		
		</td>
	</table>
</div>
<hr style="margin-top:-5px">

<div id="pageContent" style="margin-left:40px; margin-right:40px">

	<table id="adminPatientTable" class="display table-bordered table-hover">
			<thead>
				<tr>
					<th>Last Name</th>
					<th>First Name</th>
					<th> Date of Birth </th>
					<th> Age </th>
					<th> Practice </th>
					<th> Patient ID</th>
					<th/>
				</tr>
			</thead>
			
			<tbody>
				<% @records.each do |record| %>
					<tr>
						<td><%= record.last %></td>
						<td><%= record.first %></td>
						<td> <%= Time.at(record.birthdate).strftime('%m/%d/%Y') %> </td>		
						<td> <%= Time.now.year - Time.at(record.birthdate).year %></td>
						<td> <%= record.practice if record.practice != nil%></td>
						<td> <%= record.medical_record_number %> </td>
						<td> <%= link_to "View Patient Summary", :controller => "patients", :action => "show", :id => "#{record._id}"%> </td>
					</tr>
				<% end %>
			</tbody>
		</table>
		
</div>

app/views/admin/patients.html.erb
<% content_for :head do -%>
<script type="text/javascript">
  var popHealth = popHealth || {};


  $(document).ready(function() {
  });
  
</script>
<% end %>

<hr style='margin-bottom:-5px'>
<div style="padding-left:40px; padding-right:40px">
	<table class="table-condensed" style="width:100%">
		<td> <h2><strong>Patients</strong></h2> </td>
		<td colspan='2' align='right'>	
			<%= link_to "Patient List", '/admin/patient_list', :style => 'bold', :class => "btn btn-large btn-info"%> 				

			<%= link_to "Edit Practices", new_practice_path, :style => 'bold', :class => "btn btn-large btn-success"%> 	
		</td>
	</table>
</div>
<hr style="margin-top:-5px">

<div id="pageContent" style="margin-left:40px; margin-right:40px">
		
  	<div class='errorBox'>
			<u> LAST UPLOAD DETAILS </u>
			<br/>
			<b> Date: </b> <%= @last_upload_date %> <br/>
			<b> Practice: </b> <%= @last_practice_upload %> <br/>
			<b> Filename: </b> <%= $last_filename %> <br/>
			
			
			<b> Files Causing Parse Error: </b> 
				<% if $upload_errors %>
					<br/>
					<% $upload_errors.each do |er| %>
						<%= er %> &nbsp; <br/>
					<% end %>
				<% else %>
					None <br/>	
				<% end %>			
				
			<b> Providers with missing/invalid NPI: </b> <br/>
				<% if $missing_info_text %>
					<% $missing_info_text.each do |pv| %>
						<%= pv %> &nbsp; <br/>
					<% end %>
				<% end %>	
		</div>

  <table class="table-hover" style="width:60%; margin-top:-20px" >  
    <tr>
    	<td><h5>Patients Loaded: </h5></td>
      <td> <%= @patient_count %> Patients </td>
      <td> <%= button_to "Delete All Patients", "/admin/remove_patients", 'method' => 'delete', 'class' => 'btn btn-danger', :confirm=>"Are you sure you want to delete all patient records?", :style=>'margin-top:20px'%> </td>
    </tr>   
    
    <tr>
    	<td/>
      <td> <%= @unassigned_patient_count %> Unassigned Patients </td>
      <td/>
    </tr>   

    <%= form_tag("/admin/remove_practice_patients") do %>
    <tr>	
			<div class='form-inline'>
				<td> <%= label_tag "Choose practice" %> </td>
				<td> <%= select_tag "practice", options_for_select(@practices), include_blank: true%></td>					
		 		<td> <%= submit_tag "Delete Patients", class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete all patients for this practice?"}%> </td>		 			 					 				 			
		 	</div>			 
	  </tr>
    <% end %>
     
    <tr> 
    	<td><h5>Cache Counts:</h5> </td>
      <td> Query Cache: <%= @query_cache_count%> <br> Patient Cache: <%= @patient_cache_count%> </td>
      <td>
        <%= button_to "Delete Caches", "/admin/remove_caches", 'method' => 'delete', 'class' => 'btn btn-danger', :style=>'margin-top:20px'%>
   	 	</td>
    </tr>     
    <tr>
    	<td><h5> Providers loaded: </h5> </td>
      <td> <%= @provider_count%> Providers </td>
      <td> <%= button_to "Delete Providers", "/admin/remove_providers", 'method' => 'delete', 'class' => 'btn btn-danger',:style=>'margin-top:20px', confirm: "Are you sure you want to delete all provider profiles?"%> </td>
    </tr>  
    <!-- form for uploading patients -->
    <%= form_tag("/admin/upload_patients", :method => "put", :multipart=>true) do %>
      
		  <tr>
		  	<td><h5>Upload patient zip file:</h5> </td> 	  		    
		    <td type="file" id="upload_file">
	        <%= file_field_tag :file %>	      		    
		    </td> 
		  </tr>
		  
		  <tr>
			  <form class='form-inline'>
					<td> <%= label_tag "Please choose from the list of practices" %> </td>
					<td> <%= select_tag "practice", options_for_select(@practices), include_blank: true%></td>					
			 		<td> <%= submit_tag "Upload", class: 'btn btn-success', confirm: "Are you sure you want to upload patient files for chosen practice?"%> </td>		 	
			 					 				 			
			 	</form>			 
		  </tr>
    <% end %>

		<tr class= 'form-inline'>

			<td> <b> To exclude effective_date filter  </b>  </td>
			<td> <%= button_to 'Remove End Dates', "remove_end_dates", class: 'btn btn-danger' %> </td>
		</tr>
    
  </table>
  
 <br>
 <br>

</div> <!-- pageContent -->

app/views/admin/user_profile.html.erb
<div id="userProfile">
	<hr style='margin-bottom:-5px'>
		<div style="padding-left:40px; padding-right:40px">
			<table class="table-condensed" style="width:100%">
				<td> <h2><strong>User Profile:  <%= @user.full_name%> </strong></h2> </td>
			</table>
		</div>
	<hr style="margin-top:-5px">

	<%#= form_for @user do |u| %>
	<div style="margin-left:40px; margin-right:40px; margin-top:10px; width:50%">
		<table class="table table-hover table-bordered">

			<h3>Practice:  <%= @user.practice %> </h3>

			<tr>
				<td> Username: </td>
				<td> <%= @user.username %> </td>
			<tr>

			<tr>
				<td> Email: </td>
				<td> <%= @user.email %> </td>
			<tr>
	
			<tr>
				<td> Organization: </td>
				<td> <%= @user.company %> </td>
			<tr>
	
			<tr>
				<td> Organization URL: </td>
				<td> <%= @user.company_url %> </td>
			<tr>

			<tr>
				<td> Registry Name: </td>
				<td> <%= @user.registry_name %> </td>
			<tr>
	
			<tr>
				<td> Registry ID: </td>
				<td> <%= @user.registry_id %> </td>
			<tr>

			<tr>
				<td> National Provider Id: </td>
				<td> <%= @user.npi %> </td>
			<tr>

			<tr>
				<td> Tax Identifier: </td>
				<td> <%= @user.tin %> </td>
			<tr>
		</table>
		
		<div class='form-inline'>
			<%= form_tag "/admin/set_user_practice" do %>
				<%= label_tag "Assign Practice: " %>
				<%= select_tag "practice", options_for_select(Practice.distinct(:name).sort), include_blank: true%>		
				<%= hidden_field_tag(:id, @user.id) %>			
			 	<%= submit_tag "Assign", class: 'btn btn-info'%>
			<% end %>
		</div>
		
		
		<%= link_to "Back to Users", "/admin/users", :class=>"btn btn-success" %>
	</div>

</div>

app/views/admin/users.html.erb
<% content_for :head do -%>
<script type="text/javascript">
  var popHealth = popHealth || {};

  popHealth.promoteUser = function() {
    var username = $(this).data("username");
    var role = $(this).data("role");
    var parentTd = $(this).parent();
    $.post('<%= admin_promote_path %>', {'username': username, 'role': role}, function(data) {
      parentTd.html(data);
      parentTd.find('.demote').click(popHealth.demoteUser);
    });
    return false;
  };

  popHealth.demoteUser = function() {
    var username = $(this).data("username");
    var role = $(this).data("role");
    var parentTd = $(this).parent();

    if (username == '<%= current_user.username %>') {
      var response = confirm('You are about to remove admin rights from the currently logged in user' 
      +', this will cause you to immediately lose access to all admin functionality including this page.  ' 
      +'You will need to use another admin account to restore admin rights.  Are you sure you want to continue?');
      if (!response) return;
    }

    $.post('<%= admin_demote_path %>', {'username': username, 'role': role}, function(data) {
      parentTd.html(data);
      parentTd.find('.promote').click(popHealth.promoteUser);
    });
    return false;
  };

  popHealth.approveUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();
    $.post('<%= admin_approve_path %>', {'username': username}, function(data) {
      parentTd.html(data);
    });
  };

  popHealth.disableUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();

    if (username == '<%= current_user.username %>') {
      var response = confirm('You are about to disable the currently logged in user' 
      +', this will cause you to immediately lose access and be logged out.  Are you sure you want to continue?');
      if (!response) return;
    }

    popHealth.disableEnableUser(1, username, parentTd)
  };
  popHealth.enableUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();
    popHealth.disableEnableUser(0, username, parentTd)
  };
  popHealth.disableEnableUser = function(disabled, username, parentTd) {
    $.post('<%= admin_disable_path %>', {'username': username, 'disabled': disabled}, function(data) {
      parentTd.html(data);
      if (disabled == 1) parentTd.find('.disable').click(popHealth.enableUser);
      else parentTd.find('.enable').click(popHealth.disableUser);
    });
  };
  popHealth.changeNpi = function() {
    var username = $(this).data("username");
    var npi = $(this).val();
    $.post('<%= admin_update_npi_path %>', {'username': username, 'npi': npi}, function(data) {
    });
    
  };

  $(document).ready(function() {
    $('.promote').click(popHealth.promoteUser);
    $('.demote').click(popHealth.demoteUser);
    $('.approve').click(popHealth.approveUser);
    $('.enable').click(popHealth.disableUser);
    $('.disable').click(popHealth.enableUser);
    $('.npi_select').change(popHealth.changeNpi);
  
	<%# added from bstrezze %>
	$('.teamView').cluetip({
		activation: 'click',
		arrows: true,
		closePosition: 'title',
		closeText: 'Close',
		dropShadow: false,
		local: true,
		sticky: true
	});
  });
</script>
<% end -%>

<hr style='margin-bottom:-5px'>
	<div style="padding-left:40px; padding-right:40px">
		<table class="table-condensed" style="width:100%">
			<td> <h2><strong>Users</strong></h2> </td>
			<td colspan='2' align='right'>	
				<%= link_to "Refresh Tables", "users", class: "btn btn-large btn-primary", :style => "float:right" %>
			</td>
		</table>
	</div>
<hr style="margin-top:-5px">

<div id="pageContent" style="margin-left:40px; margin-right:50px; margin-top:20px">
	
	<% if flash[:notice] %>
		<font color="red"> <b> <%= flash[:notice] %> </b> </font>
		<br> </br>
	<% end %>
	
	<h5> Click on one of the tabs to view list of users: </h5>

	<div class="dropdown">
    <a class="dropdown-toggle btn btn-large btn-danger span3" data-toggle="dropdown" href="#">
   	 Admin (<%= User.where(:admin => "true").count%>)
    </a>
    <ul class="dropdown-menu" role="menu" style="width:100%; margin-top:50px">
      	<%= render partial: 'user_list', :locals => {:users => User.where(:admin => "true")} %>
    </ul>
	</div> 	
	
	<div class="dropdown">
    <a class="dropdown-toggle btn btn-large btn-info span3" data-toggle="dropdown" href="#">
   	 Providers (<%= User.where(:provider => "true", :approved =>"true").count%>)
    </a>
    <ul class="dropdown-menu" role="menu" style="width:100%; margin-top:50px">
      	<%= render partial: 'user_list', :locals => {:users => User.where(:provider => "true", :approved =>"true")} %>
    </ul>
	</div> 	
	
	<div class="dropdown">
    <a class="dropdown-toggle btn btn-large btn-success span3" data-toggle="dropdown" href="#">
   	 Staff (<%= User.where(:staff_role => "true").count%>)
    </a>
    <ul class="dropdown-menu" role="menu" style="width:100%; margin-top:50px">
      	<%= render partial: 'user_list', :locals => {:users => User.where(:staff_role => "true")} %>
    </ul>
	</div> 	
	
	<div class="dropdown">
    <a class="dropdown-toggle btn btn-large btn-warning span2" data-toggle="dropdown" href="#">
   	 Pending (<%= User.where(:approved=>'false').count%>)
    </a>
    <ul class="dropdown-menu" role="menu" style="width:100%; margin-top:50px">
      	<%= render partial: 'user_list', :locals => {:users => User.where(:approved => "false")} %>
    </ul>
	</div> 	
	
	<div class="dropdown">
    <a class="dropdown-toggle btn btn-large span2" data-toggle="dropdown" href="#">
   	 All (<%= User.all.count%>)
    </a>
    <ul class="dropdown-menu" role="menu" style="width:100%; margin-top:50px">
      	<%= render partial: 'user_list', :locals => {:users => User.all} %>
    </ul>
	</div> 	
	


</div> <!-- pageContent -->