config/routes.rb
PopHealth::Application.routes.draw do

  resources :practices
	
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_for :users do 
  	get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  
  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  put "admin/upload_patients"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
	delete "admin/remove_providers" #added for button, ssiddiqui
	delete "providers/remove"
	get "admin/user_profile"
	post "measures/export_report"
	post "measures/provider_report"
	post 'admin/remove_end_dates'
	get "admin/patient_list"
	get "measures/measure_table"
	get "admin/delete_provider"
	delete 'admin/remove_practice_patients'
	post 'admin/remove_practice_patients'
	post 'measures/export_patients'
	post "admin/set_user_practice"
	
	delete "measures/remove_selections" #added for button, ssiddiqui
	delete "logs/delete_logs"
	
	match 'admin/edit_teams/:id', :to => 'admin#edit_teams', :via => [ :get, :post ] # added from bstrezze
	match 'admin/delete_user/:id', :to => 'admin#delete_user', :via => [ :get, :post, :delete] # added by ssiddiqui

  get "logs/index"
  post "logs/index" #added for log filters
  
  match 'measures', :to => 'measures#index', :as => :dashboard, :via => :get
  match "measure/:id(/:sub_id)/providers", :to => "measures#providers", :via => :get
  match 'measure/:id(/:sub_id)', :to => 'measures#show', :as => :measure, :via => :get
  match 'measures/result/:id(/:sub_id)', :to => 'measures#result', :as => :measure_result, :via => :get
  match 'measures/definition/:id(/:sub_id)', :to => 'measures#definition', :as => :measure_definition, :via => :get
  match 'measures/patients/:id(/:sub_id)', :to => 'measures#patients', :as => :patients, :via => :get
  match 'measure/:id/select', :to => 'measures#select', :as => :select, :via => :post
  match 'measure/:id/remove', :to => 'measures#remove', :as => :remove, :via => :delete
  match 'measures/measure_patients/:id(/:sub_id)', :to=>'measures#measure_patients', :as => :measure_patients, :via=> :get
  match 'measures/measure_report', :to=>'measures#measure_report', :as => :measure_report, :via=> :get
  match 'measures/patient_list/:id(/:sub_id)', :to=>'measures#patient_list', :as => :patient_list, :via=> :get
  match 'measures/period', :to=>'measures#period', :as => :period, :via=> :post
  
  match 'provider/:npi', :to => "measures#index", :as => :provider_dashboard, :via => :get
  
  match 'records', :to => 'records#create', :via => :post
  
  match 'patients', :to => 'patients#index', :via => :get
  match 'patients/show/:id', :to => 'patients#show'
  match 'patients/toggle_excluded/:id/:measure_id(/:sub_id)', :to => 'patients#toggle_excluded', :via => :post
  
	root :to => 'measures#index'
  
  resources :measures do
    member { get :providers }
  end
  
  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end
   
    member do
      get :merge_list
      put :merge
    end
  end
  
  resources :teams
  

end

app/views/shared/_fraction.html.erb
<span class="paren">(</span>
<div class="inline-fraction">
    <span class="numeratorValue"><%= numerator %></span>
    <span class="separator"></span>
    <span class="denominatorValue"><%= denominator %></span>
</div><span class="paren">)</span>

app/views/shared/_header.html.erb
<div id="header" class="navbar">
  <div class="navbar-inner">
    <a class="brand" id="brand" style="margin-left:20px" href="/"><%= image_tag "pophealth_logo_small-trans.png" %></a>
    <ul id="mainBreadcrumbs" class="breadcrumb pull-left">
      <% if @breadcrumbs %>
        <% @breadcrumbs[0..-2].each do |crumb| %>
          <li><%= link_to(crumb.title, crumb.url) %> <span class="divider">&raquo;</span></li>
        <% end %>
        <li><%=@breadcrumbs.last.title %></li>
      <% end %>
    </ul>
  <ul class="nav pull-right">
    <li class="divider-vertical"></li>
    <li>
      <div class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="icon-user"></i>
          <% if current_user.admin? %>
          	Admin
          <% elsif current_user.practice? %>
          	<%= current_user.practice %>
          <% elsif current_user.provider? %>
         		<%= current_user.first_name %>
         	<% end %> 
        </a>
        <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="User">
          <% if APP_CONFIG['edit_account_enabled']%>
            <li><%=link_to raw('<i class="icon-edit"></i> Edit Account'), edit_user_registration_path(current_user) %></li>
          <% end %>
          <% if APP_CONFIG['logout_enabled']%>
            <li><%= link_to raw('<i class="icon-off"></i> Logout'), destroy_user_session_path, method: 'delete' %></li>
          <% end %>
          <% if current_user.staff_role? || current_user.admin? %>
           <li class="divider"></li>
          <!--<li class="dropdown-submenu">
            <a tabindex="-1" class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-star"></i> 
              Admin
            </a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="Admin">
            -->
	   	     		<li><%= link_to raw('<i class="icon-plus"></i> Providers'), providers_path%></li>           
             	<% if current_user.admin? %>
                <% if (APP_CONFIG['patient_management_enabled']) %>
                  <li><%= link_to raw('<i class="icon-eye-open"></i> Patients'), admin_patients_path%></li>
                <% end %>
                <li><%= link_to raw('<i class="icon-heart"></i> Users'), admin_users_path%></li>
               
                <li><%= link_to raw('<i class="icon-pencil"></i> Logs'), logs_index_path%></li> 
              <% end %>
           <!-- </ul>
          </li> -->
          <% end %>
        </ul>
      </div>
    </li>
    <li>
    <li class="divider-vertical"></li>
  </ul>
  
  </div>
</div>

app/views/shared/_measure_bar.html.erb
<div class="measureBarGraph">
    <div class="graph-single-bar measureBarNumerator"></div>
    <div class="graph-single-bar measureBarDenominator"></div>
    <div class="graph-single-bar measureBarExclusions"></div>
</div>

app/views/shared/_measure_metrics.html.erb
<div id="measureMetrics" style="padding:15px 0px 0px 15px;margin-bottom:20px; margin-right:40px">
  <div id="measurePopulationPercentage">
	  <%= image_tag "loading.gif", :id => "loadingAggregate", :style => "display:none;margin-top:12px" %>
  	<%= display_raw_percentage(numerator, denominator) %>
  </div>
  <%= render :partial => "shared/fraction", locals: {numerator: numerator, denominator: denominator}%>
</div>

app/views/shared/_measure_title.html.erb
<div class="span10" id="measureDetailTitle">
	<%= content_for :export_links %>
  <dl class="dl-horizontal">
    <dt>NQF ID:</dt>
      <dd>
        <span id="measureDescText">
	        <%= is_numeric?(measure['nqf_id'])? measure['nqf_id'] : "none" %>
      	</span>
      </dd>    
    <dt>Measure Name:</dt>
    	<dd>      
    	  <%= measure['name']%>
    	  <% if measure['short_subtitle']%>
    	    - <%= measure['short_subtitle'] %>
    	  <% end %>
    	</dd>
    <dt>Reporting Period:</dt>
      <dd>
        <span id="measurementPeriodStartDate"><%= Time.at(start_date).strftime("%m/%d/%Y") %> - <%= Time.at(effective_date).strftime("%m/%d/%Y") %></span>
      </dd>
    <dt>Description:</dt>
      <dd>
        <span id="measureDescText"><%= measure['description'] %></span>
      </dd>      
    </dd>
  </dl>
</div><!-- end #measureDetailTable -->

app/views/shared/_table_bar.html.erb
<div class="tableBar">
  <div class="tableBarNumerator" style="width:<%= numerator_width(numerator, patient_count)%>"><span></span></div>
  <div class="tableBarDenominator" style="width:<%= denominator_width(numerator, denominator, patient_count)%>"><span></span></div>
  <div class="tableBarExclusion" style="width:<%= exclusion_width(exclusions, patient_count)%>"><span></span></div>
</div>

app/views/shared/_top_nav.html.erb
<div id="logOut">
  Welcome, <%= current_user.first_name.to_s %>
  <span class="sep">|</span> <a href="http://projectpophealth.org/faq.html">help</a>
  <% if APP_CONFIG['edit_account_enabled']%><span class="sep">|</span> <%= link_to 'account', edit_user_registration_path(current_user) %> <% end %>
  <% if current_user.staff_role? || current_user.admin? %> <span class="sep">|</span> <a id="manage_link" href="javascript:void(0)">manage</a> <% end %>
  <% if APP_CONFIG['logout_enabled']%><span class="sep">|</span> <%= link_to 'logout', destroy_user_session_path, 'class' => 'log'%> <% end %>
  
  <ul id="manage-menu" class="ui-menu ui-widget ui-widget-content ui-corner-all dialog-menu" role="listbox" aria-activedescendant="ui-active-menuitem">
    <% if current_user.staff_role? || current_user.admin? %>
    <li class="ui-menu-item" role="menuitem" data-type="providers">
      <a class="ui-corner-all" tabindex="-1" href="<%=providers_path%>">Providers</a>
    </li>
    <% end %>
    <% if current_user.admin? %>
      <li class="ui-menu-item" role="menuitem" data-type="users">
        <a class="ui-corner-all" tabindex="-1" href="<%=admin_users_path%>">Users</a>
      </li>
      
      <% if (APP_CONFIG['patient_management_enabled']) %>
      <li class="ui-menu-item" role="menuitem" data-type="patients">
        <a class="ui-corner-all" tabindex="-1" href="<%=admin_patients_path%>">Patients</a>
      </li>
      <% end %>

      <li class="ui-menu-item" role="menuitem" data-type="logs">
        <a class="ui-corner-all" tabindex="-1" href="<%= logs_index_path%>">Logs</a>
      </li>
    <% end %>
    
  </ul>
  
  <script type="text/javascript">
    var popHealth = popHealth || {};
  
    $(document).ready(function() {
      $('#manage_link').hover(popHealth.manageMenuIn, popHealth.manageMenuOut)
      $('#manage_link').mousemove(popHealth.manageMenuIn)
      $('.dialog-menu li a').hover(function() { $(this).addClass('ui-state-hover') } , function() { $(this).removeClass('ui-state-hover')} )
		});
		
    popHealth.manageMenuOut = function(data) {
    }
    popHealth.manageMenuIn = function(data) {
      position = $(this).offset()
      dialog = $( "#manage-menu" ).dialog({ position: [position.left - 2, (position.top + $(this).height() - $(window).scrollTop())], resizable: false, dialogClass: 'dialog-menuwindow', minWidth: false, minHeight: false, width: 100 }).css('padding', '2px');
      dialog.hover(popHealth.manageDialogHoverIn, popHealth.manageDialogHoverOut )
      $(this).hover(function() {}, popHealth.manageMenuHoverOut)
    }
    popHealth.manageMenuHasMouse=false;
    popHealth.manageDialogHoverIn = function() {
      popHealth.manageMenuHasMouse=true
    }
    popHealth.manageDialogHoverOut = function() {
      popHealth.manageMenuHasMouse=false;
      popHealth.closeDialog();
    }
    popHealth.closeDialog = function() {
      if (!popHealth.manageMenuHasMouse) {
        dialog.dialog('close'); 
        popHealth.manageMenuHasMouse=false;
      } else {
        setTimeout(popHealth.closeDialog, 600);
      }
    }
    
    popHealth.manageMenuHoverOut = function() {
      setTimeout(popHealth.closeDialog, 600) 
    }
		
    
  </script>
  
</div>