config/routes.rb
PopHealth::Application.routes.draw do

  resources :practices
	
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_for :users do 
  	get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  
  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  put "admin/upload_patients"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
	delete "admin/remove_providers" #added for button, ssiddiqui
	delete "providers/remove"
	get "admin/user_profile"
	post "measures/export_report"
	post "measures/provider_report"
	post 'admin/remove_end_dates'
	get "admin/patient_list"
	get "measures/measure_table"
	get "admin/delete_provider"
	delete 'admin/remove_practice_patients'
	post 'admin/remove_practice_patients'
	post 'measures/export_patients'
	post "admin/set_user_practice"
	
	delete "measures/remove_selections" #added for button, ssiddiqui
	delete "logs/delete_logs"
	
	match 'admin/edit_teams/:id', :to => 'admin#edit_teams', :via => [ :get, :post ] # added from bstrezze
	match 'admin/delete_user/:id', :to => 'admin#delete_user', :via => [ :get, :post, :delete] # added by ssiddiqui

  get "logs/index"
  post "logs/index" #added for log filters
  
  match 'measures', :to => 'measures#index', :as => :dashboard, :via => :get
  match "measure/:id(/:sub_id)/providers", :to => "measures#providers", :via => :get
  match 'measure/:id(/:sub_id)', :to => 'measures#show', :as => :measure, :via => :get
  match 'measures/result/:id(/:sub_id)', :to => 'measures#result', :as => :measure_result, :via => :get
  match 'measures/definition/:id(/:sub_id)', :to => 'measures#definition', :as => :measure_definition, :via => :get
  match 'measures/patients/:id(/:sub_id)', :to => 'measures#patients', :as => :patients, :via => :get
  match 'measure/:id/select', :to => 'measures#select', :as => :select, :via => :post
  match 'measure/:id/remove', :to => 'measures#remove', :as => :remove, :via => :delete
  match 'measures/measure_patients/:id(/:sub_id)', :to=>'measures#measure_patients', :as => :measure_patients, :via=> :get
  match 'measures/measure_report', :to=>'measures#measure_report', :as => :measure_report, :via=> :get
  match 'measures/patient_list/:id(/:sub_id)', :to=>'measures#patient_list', :as => :patient_list, :via=> :get
  match 'measures/period', :to=>'measures#period', :as => :period, :via=> :post
  
  match 'provider/:npi', :to => "measures#index", :as => :provider_dashboard, :via => :get
  
  match 'records', :to => 'records#create', :via => :post
  
  match 'patients', :to => 'patients#index', :via => :get
  match 'patients/show/:id', :to => 'patients#show'
  match 'patients/toggle_excluded/:id/:measure_id(/:sub_id)', :to => 'patients#toggle_excluded', :via => :post
  
	root :to => 'measures#index'
  
  resources :measures do
    member { get :providers }
  end
  
  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end
   
    member do
      get :merge_list
      put :merge
    end
  end
  
  resources :teams
  

end

app/controllers/measures_controller.rb
require 'ostruct'
class MeasuresController < ApplicationController
  include MeasuresHelper

  before_filter :authenticate_user!
  before_filter :validate_authorization!
  before_filter :filter_order
  after_filter :hash_document, :only => :measure_report
  
  # fixed by ssiddiqui. order important to establish selected_provider first
  def filter_order
  	setup_filters
  	set_up_environment 
  end

  add_breadcrumb_dynamic([:definition, :selected_provider], only: %w{show patients})  do |data| 
    measure = data[:definition]; provider = data[:selected_provider]
    {title: "#{measure['endorser']}" + "NQF#" + "#{measure['nqf_id']}" + (measure['sub_id'] ? "#{measure['sub_id']}" : ''), 
     url: "#{Rails.configuration.relative_url_root}/measure/#{measure['id']}"+(measure['sub_id'] ? "/#{measure['sub_id']}" : '')+(provider ? "?npi=#{provider.npi}" : "/providers")}
  end
  add_breadcrumb 'Parameters', '', only: %w{show}
  add_breadcrumb 'Patients', '', only: %w{patients}
  
  def index
    @categories = HealthDataStandards::CQM::Measure.categories    
    @last_upload_date = Log.where(:event => 'patient record imported').last.created_at.in_time_zone('Eastern Time (US & Canada)').ctime if (Log.where(:event => 'patient record imported').count() > 0)
  end

	def measure_table 
	end
	
  def show
    respond_to do |wants|
      wants.html do
        build_filters if (@selected_provider)
        generate_report
        @result = @quality_report.result
      end
      wants.json do
        measures = params[:sub_id] ? QME::QualityMeasure.get(params[:id], params[:sub_id]) : QME::QualityMeasure.sub_measures(params[:id])
        
        render_measure_response(measures, params[:jobs]) do |sub|
          {
            report: QME::QualityReport.new(sub['id'], sub['sub_id'], 'effective_date' => @effective_date, 'filters' => @filters, 'oid_dictionary' => @oid_dictionary),
            patient_count: @patient_count
          }
        end
      end
    end
  end
      
  def definition
    render :json => @definition
  end
  
  def result
    uuid = generate_report(params[:uuid])
    if (@result)
      render :json => @result
    else
      render :json => @quality_report.status(uuid)
    end  
  end  
  
  def providers    
    authorize! :manage, :providers
    
    respond_to do |wants|
      wants.html {}
      wants.js do    
      #  @providers = Provider.page(params[:page]).per(20).userfilter(current_user).alphabetical
       	@providers = Provider.user_filter(current_user) # added by ssiddiqui
        @providers = @providers.any_in(team_id: params[:team]) if params[:team]      	 
      end
      
      wants.json do
        providerIds = params[:provider].blank? ?  Provider.all.map { |pv| pv.id.to_s } : @filters.delete('providers')
        render_measure_response(providerIds, params[:jobs]) do |pvId|
          filters = @filters ? @filters.merge('providers' => [pvId]) : {'providers' => [pvId]}
          { 
            report: QME::QualityReport.new(params[:id], params[:sub_id], 'effective_date' => @effective_date, 'filters' => filters),
            patient_count: @patient_count
          }
        end
      end
    end
  end
  
  def remove
    SelectedMeasure.remove_measure(current_user.username, params[:id])
    render :text => 'Removed'
  end
  
	# ADDED FOR CLEAR SELECTION BUTTON - ssiddiqui
	def remove_selections
    SelectedMeasure.remove_all(current_user.username)
    redirect_to(:back)
  end

  def select
    SelectedMeasure.add_measure(current_user.username, params[:id])
    render :text => 'Select'
  end
  
  def patients
    build_filters if (@selected_provider)
    generate_report
  end

	def export_patients
		type = params['type']
		
		book = Spreadsheet::Workbook.new
		sheet = book.create_worksheet
		format = Spreadsheet::Format.new :weight => :bold
		today = Time.now.strftime("%D")
	
		# table headers
		sheet.row(0).push 'MRN', 'First Name', 'Last Name', 'Gender', 'Birthdate'
		sheet.row(0).default_format = format
		r=1;
		
		# measure info
		value_type = "value." + "#{type}";
		query = { 'value.measure_id' => params[:measure_id], 'value.sub_id' => params[:sub_id], 'value.effective_date' => @effective_date, "#{value_type}" => 1} 				
		cache = PatientCache.where( query )
		practice = @current_user.practice	;		
		selected_provider = Provider.where(:npi => params[:npi] ).first
		
		if @current_user.admin? && !(selected_provider) 
			cache.each do |pc|
				sheet.row(r).push pc.value['medical_record_id'], pc.value['first'], pc.value['last'], pc.value['gender'], Time.at(pc.value['birthdate']).strftime("%D") 
				r = r+1;
			end	
		elsif @current_user.staff_role? && (selected_provider) # if staff
			cache.each do |pc|
				pc_record = Record.where( :medical_record_number => pc.value['medical_record_id'] ).first
				pc_practice = pc_record.practice == practice
				pc_performer = (pc_record.provider_performances.any? {|perf| perf.provider_id == selected_provider._id});						
								
				if pc_practice && pc_performer 
					sheet.row(r).push pc.value['medical_record_id'], pc.value['first'], pc.value['last'], pc.value['gender'], Time.at(pc.value['birthdate']).strftime("%D")
					r = r+1;
				end
			end		
		elsif @current_user.staff_role? && !(selected_provider) # if staff
			cache.each do |pc|
				pc_record = Record.where( :medical_record_number => pc.value['medical_record_id'] ).first
				pc_practice = pc_record.practice == practice												
				if pc_practice 
					sheet.row(r).push pc.value['medical_record_id'], pc.value['first'], pc.value['last'], pc.value['gender'], Time.at(pc.value['birthdate']).strftime("%D")
					r = r+1;
				end
			end
		elsif @current_user.provider? || selected_provider
			cache.each do |pc|
				npi = (selected_provider)? selected_provider.npi : @current_user.npi
			  prov = Provider.where(:npi => npi).first
			  if pc.value['provider_performances'].any?{ |perf| perf['provider_id'] == prov._id }
			  	sheet.row(r).push pc.value['medical_record_id'], pc.value['first'], pc.value['last'], pc.value['gender'], Time.at(pc.value['birthdate']).strftime("%D")
					r = r+1;
			  end
			end
		end
		
		# if admin, then do all of them. else practice wise
		filename = "patients_" + "#{type}" + "_" + "#{today}" + ".xls"
		
		data = StringIO.new '';
		book.write data;
		send_data(data.string, {
		  :disposition => 'attachment',
		  :encoding => 'utf8',
		  :stream => false,
		  :type => 'application/excel',
		  :filename => filename
		})
		
#		redirect_to measures_patients_path( @definition => params['definition'])
	end


	# creates spreadsheet of dashboard reports
 	def export_report
  	book = Spreadsheet::Workbook.new
		sheet = book.create_worksheet
		
		format = Spreadsheet::Format.new :weight => :bold
		
		selected_measures = @current_user.selected_measures
		
		start_date = Time.at(@period_start).strftime("%D")
    end_date = Time.at(@effective_date).strftime("%D")
    
		# table headers
		sheet.row(0).push 'NQF ID', 'Sub ID', 'Name', 'Subtitle', 'Numerator', 'Denominator', 'Exclusions', 'Percentage', 'Aggregate'
		sheet.row(0).default_format = format
		r = 1
		
		selected_provider = @selected_provider || Provider.where(:npi => params[:npi]).first
		providers_for_filter = (selected_provider)? selected_provider._id.to_s : @providers.map{|pv| pv._id.to_s}
		
		# populate rows
		selected_measures.each do |measure|
			subs_iterator(measure['subs']) do |sub_id|
				info = measure_info(measure['id'], sub_id)

				if selected_provider != nil
					query = {:measure_id => measure['id'], :sub_id => sub_id, :effective_date => @effective_date, 'filters.providers' => [selected_provider._id.to_s] }
				else
					query = {:measure_id => measure['id'], :sub_id => sub_id, :effective_date => @effective_date, 'filters.providers' => {'$all' => providers_for_filter}, 'filters.providers' => {'$size' => providers_for_filter.count} }
				end
				
				cache = MONGO_DB['query_cache'].find(query).first
				percent =  percentage(cache['NUMER'].to_f, cache['DENOM'].to_f)
				full_percent = percentage(cache['full_numer'].to_f, cache['full_denom'].to_f)
				sheet.row(r).push info[:nqf_id], sub_id, info[:name], info[:subtitle], cache['NUMER'], cache['DENOM'], cache['DENEX'] , percent, full_percent 
				r = r + 1;
			end
		end
	
		today = Time.now.strftime("%D")
		if @selected_provider
			filename = "measure-report-" + "#{@selected_provider.npi}-" + "#{today}" + ".xls"	
		else	
			filename = "measure-report-" + "#{today}" + ".xls"
		end
		data = StringIO.new '';
		book.write data;
		send_data(data.string, {
		  :disposition => 'attachment',
		  :encoding => 'utf8',
		  :stream => false,
		  :type => 'application/excel',
		  :filename => filename
		})
  end 
  
  def provider_report
    book = Spreadsheet::Workbook.new
		sheet = book.create_worksheet
		measure_id = params[:measure_id]
		sub_id = params[:sub_id]
		format = Spreadsheet::Format.new :weight => :bold
		    
		# table headers
		sheet.row(0).push 'First Name', 'Last Name', 'Numerator', 'Denominator', 'Exclusions', 'Percentage'
		sheet.row(0).default_format = format
		r = 1
		
		provider_list = Provider.user_filter(@current_user).map {|pv| pv._id}
		
		provider_list.each do |prov|
		  provider = Provider.where(:_id => prov).first	  
  		cache = MONGO_DB['query_cache'].find(
  		  :measure_id => measure_id, 
  		  :sub_id => sub_id, 
  		  :effective_date => @effective_date, 
  		  'filters.providers' => [prov.to_s]).first
  		if (cache['NUMER'] != nil)
  		  percent =  percentage(cache['NUMER'].to_f, cache['DENOM'].to_f)
  		  sheet.row(r).push provider.family_name, provider.given_name, cache['NUMER'], cache['DENOM'], cache['DENEX'] , percent
				r = r + 1;
  		end
  	end
		nqf = measure_info(measure_id, sub_id)[:nqf_id]	
		today = Time.now.strftime("%D")
		filename = "provider-report-" + "NQF" + "#{nqf}" + "-" + "#{today}" + ".xls"
		
		data = StringIO.new '';
		book.write data;
		send_data(data.string, {
		  :disposition => 'attachment',
		  :encoding => 'utf8',

app/helpers/measures_helper.rb
module MeasuresHelper
  # Helper for iterating through the sub ids for a measure. For measures that do not have any sub ids
  # this method will loop once passing in nil as a sub id
  def subs_iterator(measure_subs)
    subs = nil
    if measure_subs.empty?
      subs = [nil]
    else
      subs = measure_subs
    end
    subs.each do |sub_id|
      yield sub_id
    end
  end
 	
	# added from bstrezze
  # Checks a measure id to see if it is in the Array returned
  # be getting the selected_measure collection
  def measure_selected(measure_id, selected_measures)
    is_selected?(measure_id, selected_measures) ? 'checked' : nil
  end
  
  def is_numeric?(obj) 
   obj.to_s.match(/\A[+-]?\d+?(\.\d+)?\Z/) == nil ? false : true
	end
  
  def display_row(measure_id, selected_measures)
    is_selected?(measure_id, selected_measures) ? "" : "display:none"
  end
  
  def display_header(measures, selected_measures)
    (measures.map { |m| m['id'] } & selected_measures.map { |m| m['id'] }).empty? ? "display:none" : ""
  end
  
  def display_provider(provider, index, page)
     ((page - 1) * 10 <= index) && index < (page * 10) ? "" : "display:none"
  end
  
  def is_selected?(measure_id, selected_measures)
    selected_measures.any? {|measure| measure['id'] == measure_id}
  end
  
  def value_or_default(results, field, default)
    results[field] || default
  end
  
  def percentage(results)
    raw_percentage(value_or_default(results, 'numerator', 0), value_or_default(results, 'denominator', 0))
  end
  
  def display_raw_percentage(numerator, denominator)
    output = raw_percentage(numerator, denominator)
    if output
      "#{output}%"
    end
  end
  
  def raw_percentage(numerator, denominator)
    return unless denominator
    if denominator > 0
      ((numerator / denominator.to_f) * 100).to_i
    else
      0
    end
  end
  
  # get race name from code
  def get_race_name(param)
		rec = ""
		Race.all.each do |race|
			race["codes"].each do |code|
		  	if code == param
		  		rec = race.name
		  	end
		  end 
		end
		rec
	end
	
	def get_ethnicity_name(param)
		rec = ""
		Ethnicity.all.each do |eth|
			eth["codes"].each do |code|
		  	if code == param
		  		rec = eth.name
		  	end
		  end 
		end
		rec
	end
  # def numerator_width(results)
  #     # raise results['numerator'].inspect
  #     if results['numerator']
  #       raise results.inspect
  #       "#{((results['numerator'] / results['patient_count'].to_f) * 100).to_i}%"      
  #     else
  #       '33%'
  #     end
  #   end
  #   
  #   def denominator_width(results)
  #     if results['numerator'] && results['denominator']
  #       "#{(((results['denominator'] - results['numerator'])/ results['patient_count'].to_f) * 100).to_i}%"
  #     else
  #       '33%'
  #     end
  #   end

  def dob(time)
    if time
      Time.at(time).strftime("%m/%d/%Y").to_s
    else 
      nil
    end
  end

  def age_from_time(time)
    if (time)
      t = Time.now.to_i - time
      year = 365 * 24 * 60 * 60
      (t/year).to_i
    else
      nil
    end
  end
  
  def result_hash(measure_id, sub_id, effective_date, filters)
    qr = QME::QualityReport.new(measure_id, sub_id, 'effective_date' => effective_date, 'filters' => filters)
    result = {'patient_count' => @patient_count}
    if qr.calculated?
      result.merge!(qr.result)
    else
      result['uuid'] = qr.calculate
    end
    
    result
  end
  
  def measure_stats_div(measure_id, sub_id, effective_date, filters)
    results = result_hash(measure_id, sub_id, effective_date, filters)
    div_options = {:class => 'tableMeasureCtrl', :"data-measure-id" => measure_id}
    div_options[:"data-measure-sub-id"] = sub_id if sub_id
    div_options[:"data-calculation-job-uuid"] = results['uuid'] if results['uuid']
    content_tag(:div, div_options) do
      yield results
    end
  end
end

app/views/measures/_measure.html.erb
<% subs_iterator(measure['subs']) do |sub| %> 
	<div data-measure="<%=measure['id']%>" data-measure-sub="<%= sub['sub_id']%>" style="<%=display_row(measure['id'], current_user.selected_measures)%>" class="measure row-fluid">

		<div class="measure-subtitle span1">
			NQF# <%=measure['nqf_id'] unless (measure['nqf_id'].to_i == 0)%> <%= sub['sub_id']%>
		</div>

		<div class="span3 measure-name">
		  <% if sub['sub_id'].nil? || sub['sub_id'] == 'a' %>
		    <div data-placement="bottom" data-original-title="<%=measure['description']%>" rel="tooltip">
		      <% if (can? :manage, :providers) %>
		        <%= link_to(measure['name'], "#{measure_path(measure['id'], sub['sub_id'])}/providers") %>
		      <% else %>
		        <span><%= measure['name'] %></span>
		      <% end %>
		    </div>
		   <% end %>
		</div>		
			
		<div class="measure-subtitle span1">
		  <% if (can? :manage, :providers) %>
		    <%= link_to("#{sub['short_subtitle']}", "#{measure_path(measure['id'], sub['sub_id'])}/providers") %>
		  <% else %>
		    <%= sub['short_subtitle'] %>
		  <% end %>
		</div>
		
			
		<div class="measure_chart span2">
			<%= render :partial => "shared/measure_bar"%>
		</div>

		<div class="measure_fraction span1" style="text-align: center">
				<%= render :partial => "shared/fraction", locals: {numerator: 0, denominator: 0} %>
		</div>
	
		<div class="user_percentage span1">	
		 		<%= image_tag "loading.gif" %>
		</div>   

		<div class="full_percentage span1">
				<%= image_tag "loading.gif"%>	
		</div>

		<div class="span1" style="padding-left:40px">		
			<%npi_param = (@selected_provider ? "?npi=#{@selected_provider.npi}" : '')%>
			<%= link_to 'Parameters', measure_url(measure['id'], sub['sub_id'])+npi_param%>
			<%= link_to 'Patients', patients_url(measure['id'], sub['sub_id'])+npi_param%>  
		</div>
	
	</div>
<% end %> 

app/views/measures/_provider_row.html.erb
<div class="provider row-fluid" data-provider="<%=provider_row.id%>">
  <div class="span2"><%= link_to "#{provider_row.family_name.upcase} , #{provider_row.given_name}", measures_path(npi: provider_row.npi) %>
  </div>
  <div class="percent span1" style="font-size: 15px">
    <div class="measureProviderPopulationPercentage"></div>
  </div>
  <div class="fraction span1">
    <%= render :partial => "shared/fraction", locals: {numerator: 0, denominator: 0} %>
  </div>
  
  <div class="provider_row_measure_bar span2">
    <%= render :partial => "shared/measure_bar"%>
  </div>
</div>

app/views/measures/patients.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    function llog(x) {}

    var popHealth = popHealth || {};
    var sort = "_id";
    var offset = 0;
    var limit = 20;
    var display_type= "denominator";
    var effective_date = <%=Time.gm(2010, 12, 31).to_i%>;
    var measure_id= '<%==params[:id] %>';
    var sub_id= '<%==params[:sub_id] %>';
    var sort_ascending = true;

    popHealth.drawPctChart = function(data) {
      if (data.complete) {
        data = data.result[0]
        var elem = "#measureMetrics";
        var percent = data.DENOM > 0 ? Math.floor((data.NUMER/data.DENOM)*100) : 0;
        var numeratorWidth = (data.numerator/<%= @patient_count %>).toFixed(2)*100;
        var denominatorWidth = data.DENOM > 0 ? ((data.DENOM - data.NUMER)/<%= @patient_count %>).toFixed(2)*100 : 0;
      
        $(elem).find(".numeratorValue").text(data.NUMER);
        $(elem).find(".denominatorValue").text(data.DENOM);
        $("#measurePopulationPercentage").text(percent + "%");
        console.log(data)
        $("#numeratorCount").text(data.NUMER);
        $("#denominatorCount").text(data.DENOM);
        $("#antiNumeratorCount").text(data.antinumerator);
        $("#exclusionsCount").text(data.DENEX);
        $("#exceptionsCount").text(data.DENEXCEP);
        display_type=$('input:radio[name=patientGroup]:checked').data('type')
      
        popHealth.reloadTable();
      }
    }

    popHealth.renderMeasureJSON = function(data) {
        var measure = data;
    }

    popHealth.reloadTable = function(data){
      $('#patientTableContainer').html("<div style='padding: 150px;'><img src='/assets/loading_bar.gif'/></div>");
      var params = ''
      <% if (@selected_provider) %> params = '?npi=<%= @selected_provider.npi %>';<%end%>
      var url = "<%= Rails.configuration.relative_url_root %>/measures/measure_patients/"+measure_id;
      if (sub_id) {
         url += "/"+sub_id
      }
      url += params
      $.ajax({ url: url,
               data: {sort:sort, sort_order:(sort_ascending? 'asc' :'desc' ) , offset:offset, limit:limit, type:display_type, effective_date:effective_date },
               type: "GET",
               dataType: 'html',
               success: function(res){
                 $('#patientTableContainer').html(res);
               },
               error: function(xhr, err) {
                 alert("We encountered an error rendering the popHealth UI.");
               }
             });
    }

    popHealth.sortPatientTable = function(field){
      sort = field;
      popHealth.reloadTable();
    }
    
    popHealth.poll = function() {
      var qr = new QualityReport('<%=@definition['id']%>', '<%=@definition['sub_id']%>');
      var params = {}
      <% if (@selected_provider) %> params['npi'] = '<%= @selected_provider.npi %>';<%end%>
      qr.poll(params, popHealth.drawPctChart);
    }

    $(document).ready(function() {
      //$.getJSON("json/bp.json",popHealth.renderMeasureJSON);
      $.getJSON("<%= measure_definition_url(@definition['id'], @definition['sub_id']) %>",popHealth.renderMeasureJSON);
      $("#measurementPeriodEndDate").val(new Date().format("mm/dd/yyyy"));
      $("#btnSaveNewMeasure").click(popHealth.saveNewMeasure);
      $("#btnReturnToDash").click(popHealth.returnToDash);
      $("#btnExportExcel").click(function() {window.location = '<%= patient_list_url(params[:id], params[:sub_id], :format => :xml) + (@selected_provider ? "?npi=#{@selected_provider.npi}":'') %>'})

      $('button.patientGroup').click(function() {
        //$('#patientTableContainer').patient_table.displayNumerator();
        $("button.patientGroup").removeClass("active")
        $(this).addClass("active")
        if(this.id == "num"){
          display_type = "NUMER";
        } else if(this.id == "den"){
            display_type = "DENOM";
        } else if(this.id == "exc"){
            display_type = "DENEX";
        } else if(this.id == 'denexc') {
            display_type = "DENEXCEP"
        } else {
            display_type = "antinumerator";
        }
        popHealth.reloadTable();
      });
      
      popHealth.poll();
      
    });
  var results = <%=@result.to_json.html_safe %>;
  </script>
<% end %>

<div id="pageContent" class="row-fluid" style="margin-left:20px; margin-right:20px">
	
	
  <div style="align:left;" class='span2' >  
	  <div>
	    <%= render :partial => 'shared/measure_metrics', locals: {numerator: (@result ? @result['numerator'] : 0), denominator: (@result ? @result['denominator'] : 0)} %>
	  </div>  
		
	  <div style="margin-top:10px" class="row-fluid btn-group btn-group-vertical">
	    <button id="num" href="#" class="patientGroup btn btn-success btn-large span12">
	    	Numerator<span id="numeratorCount" class="badge badge-inverse pull-left"></span>
	    </button>
	    <button id="den" href="#" class="active patientGroup btn btn-info btn-large span12">
	    	Denominator<span id="denominatorCount" class="badge badge-inverse pull-left"></span>
	    </button>
	    <button id="anti" href="#" class="patientGroup btn btn-danger btn-large span12">
	    	Outliers<span id="antiNumeratorCount" class="badge badge-inverse pull-left"></span>
	    </button>
	    <button id="exc" href="#" class="patientGroup btn btn-warning btn-large span12">
	    	Exclusions<span id="exclusionsCount" class="badge badge-inverse pull-left"></span></button>
	    <button id="denexc" href="#" class="patientGroup btn btn-inverse btn-large span12">
	    	Exceptions<span id="exceptionsCount" class="badge badge-inverse pull-left"></span>
	   	</button>
	  </div>
	</div>
	
  <div id="dashboardPeriod"  class="span10 row-fluid" >
		<div>
			<% if @selected_provider %>
				<h3> Provider: <%= @selected_provider.full_name %> </h3>
			<% end %>
			
    	<%= render :partial => 'shared/measure_title', locals: {measure: @definition, start_date: @period_start, effective_date: @effective_date }%>
		</div>
  
  	<div class='row-inline' >
			<div class="btn-group" >
          <%= link_to 'providers', "#{measure_path(@definition['id'], @definition['sub_id'])}/providers", method: 'get', :class => 'tableEdit btn btn-danger', :style =>'width:100px'%> 
          <%= link_to 'parameters', measure_url(@definition['id'], @definition['sub_id']), method: 'get', :class => 'tableEdit btn btn-info', :style =>'width:100px'%> 
	    </div>
	    
	    <div class="form-inline" style="float:right; margin-right:20px" >
	    	<%= form_tag measures_export_patients_path(npi: params[:npi], measure_id: @definition['id'], sub_id: @definition['sub_id']) do %>
					<%= select_tag "type", 
						options_for_select([				
							['Numerators', 'NUMER'],
							['Denominators', 'DENOM'],
							['Outliers', 'antinumerator']
						])						
					%> 
		 			<%= submit_tag "Export", class: 'btn btn-success' %>
		 			<% end %>
		 	</div>			 
		</div>		
  
  
    <br style="clear:left"/>
    <div id="patientTableContainer" style="height:500px; overflow-y:scroll;"> 
      <div style="padding: 50px;"><img src="/assets/loading_bar.gif"/></div>
    </div><!-- end patientTableContainer -->
  </div> <!-- end dashboardPeriod -->
</div><!-- end #pageContent -->

app/views/measures/period.js.erb
{
  "start": "<%= Time.at(@period_start).strftime("%m/%d/%Y") %>",
  "end": "<%= Time.at(@effective_date).strftime("%m/%d/%Y") %>"
}